#ifndef __SAULE_ENGINE_DEFINE_HPP__
# define __SAULE_ENGINE_DEFINE_HPP__ 1

#ifdef SAULE_ENGINE_USE_OPENGL
# ifdef SAULE_ENGINE_USE_VULKAN
#  error "can't use multiple GPU API, at same time."
# endif
# define SAULE_ENGINE_VERTEX_SHADER GL_VERTEX_SHADER
# define SAULE_ENGINE_FRAGMENT_SHADER GL_FRAGMENT_SHADER
# define SAULE_ENGINE_FLOAT GL_FLOAT
# define SAULE_ENGINE_UINT GL_UNSIGNED_INT
#endif

/*
	--TODO--
	Shader Type
*/
// # define SAULE_ENGINE_VERTEX_SHADER 1	// GL_VERTEX_SHADER
// # define SAULE_ENGINE_FRAGMENT_SHADER 2	// GL_FRAGMENT_SHADER

/*
	--TODO--
	Type Define
*/
// # define SAULE_ENGINE_FLOAT 1	// GL_FLOAT
// # define SAULE_ENGINE_UINT 2	// GL_UNSIGNED_INT

/*
	--TODO--
	Implement Vulkan
*/
#ifdef SAULE_ENGINE_USE_VULKAN
# ifdef SAULE_ENGINE_USE_OPENGL
#  error "can't use multiple GPU API, at same time."
# endif
// Vulkan is not impelemted for now
# error "Vulkan is not implemented for now"
#endif

/*
	Math Value
*/
# define SAULE_ENGINE_PI 3.1415926535897932384626433832795

/*
	Default Texture/Material
*/
# define SAULE_ENGINE_DEFAULT_SPECULAR_HIGHLIGHTS 250.0f
# define SAULE_ENGINE_DEFAULT_AMBIENT_COLOR 1.0f, 1.0f, 1.0f
# define SAULE_ENGINE_DEFAULT_DIFFUSE_COLOR 1.0f, 1.0f, 1.0f
# define SAULE_ENGINE_DEFAULT_SPECULAR_COLOR 0.5f, 0.5f, 0.5f
# define SAULE_ENGINE_DEFAULT_EMISSIVE_COLOR 0.0f, 0.0f, 0.0f
# define SAULE_ENGINE_DEFAULT_OPTICAL_DENSITY 1.0f
# define SAULE_ENGINE_DEFAULT_DISSOLVE 1.0f

/*
	Key code
*/

#define SAULE_ENGINE_KEY_SPACE	GLFW_KEY_SPACE
#define SAULE_ENGINE_KEY_APOSTROPHE	GLFW_KEY_APOSTROPHE /* ' */
#define SAULE_ENGINE_KEY_COMMA	GLFW_KEY_COMMA /* , */
#define SAULE_ENGINE_KEY_MINUS	GLFW_KEY_MINUS /* - */
#define SAULE_ENGINE_KEY_PERIOD	GLFW_KEY_PERIOD /* . */
#define SAULE_ENGINE_KEY_SLASH	GLFW_KEY_SLASH /* / */
#define SAULE_ENGINE_KEY_0	GLFW_KEY_0
#define SAULE_ENGINE_KEY_1	GLFW_KEY_1
#define SAULE_ENGINE_KEY_2	GLFW_KEY_2
#define SAULE_ENGINE_KEY_3	GLFW_KEY_3
#define SAULE_ENGINE_KEY_4	GLFW_KEY_4
#define SAULE_ENGINE_KEY_5	GLFW_KEY_5
#define SAULE_ENGINE_KEY_6	GLFW_KEY_6
#define SAULE_ENGINE_KEY_7	GLFW_KEY_7
#define SAULE_ENGINE_KEY_8	GLFW_KEY_8
#define SAULE_ENGINE_KEY_9	GLFW_KEY_9
#define SAULE_ENGINE_KEY_SEMICOLON	GLFW_KEY_SEMICOLON /* ; */
#define SAULE_ENGINE_KEY_EQUAL	GLFW_KEY_EQUAL /* = */
#define SAULE_ENGINE_KEY_A	GLFW_KEY_A
#define SAULE_ENGINE_KEY_B	GLFW_KEY_B
#define SAULE_ENGINE_KEY_C	GLFW_KEY_C
#define SAULE_ENGINE_KEY_D	GLFW_KEY_D
#define SAULE_ENGINE_KEY_E	GLFW_KEY_E
#define SAULE_ENGINE_KEY_F	GLFW_KEY_F
#define SAULE_ENGINE_KEY_G	GLFW_KEY_G
#define SAULE_ENGINE_KEY_H	GLFW_KEY_H
#define SAULE_ENGINE_KEY_I	GLFW_KEY_I
#define SAULE_ENGINE_KEY_J	GLFW_KEY_J
#define SAULE_ENGINE_KEY_K	GLFW_KEY_K
#define SAULE_ENGINE_KEY_L	GLFW_KEY_L
#define SAULE_ENGINE_KEY_M	GLFW_KEY_M
#define SAULE_ENGINE_KEY_N	GLFW_KEY_N
#define SAULE_ENGINE_KEY_O	GLFW_KEY_O
#define SAULE_ENGINE_KEY_P	GLFW_KEY_P
#define SAULE_ENGINE_KEY_Q	GLFW_KEY_Q
#define SAULE_ENGINE_KEY_R	GLFW_KEY_R
#define SAULE_ENGINE_KEY_S	GLFW_KEY_S
#define SAULE_ENGINE_KEY_T	GLFW_KEY_T
#define SAULE_ENGINE_KEY_U	GLFW_KEY_U
#define SAULE_ENGINE_KEY_V	GLFW_KEY_V
#define SAULE_ENGINE_KEY_W	GLFW_KEY_W
#define SAULE_ENGINE_KEY_X	GLFW_KEY_X
#define SAULE_ENGINE_KEY_Y	GLFW_KEY_Y
#define SAULE_ENGINE_KEY_Z	GLFW_KEY_Z
#define SAULE_ENGINE_KEY_LEFT_BRACKET	GLFW_KEY_LEFT_BRACKET /* [ */
#define SAULE_ENGINE_KEY_BACKSLASH	GLFW_KEY_BACKSLASH /* \ */
#define SAULE_ENGINE_KEY_RIGHT_BRACKET	GLFW_KEY_RIGHT_BRACKET /* ] */
#define SAULE_ENGINE_KEY_GRAVE_ACCENT	GLFW_KEY_GRAVE_ACCENT /* ` */
#define SAULE_ENGINE_KEY_WORLD_1	GLFW_KEY_WORLD_1 /* non-US #1 */
#define SAULE_ENGINE_KEY_WORLD_2	GLFW_KEY_WORLD_2 /* non-US #2 */
#define SAULE_ENGINE_KEY_ESCAPE	GLFW_KEY_ESCAPE
#define SAULE_ENGINE_KEY_ENTER	GLFW_KEY_ENTER
#define SAULE_ENGINE_KEY_TAB	GLFW_KEY_TAB
#define SAULE_ENGINE_KEY_BACKSPACE	GLFW_KEY_BACKSPACE
#define SAULE_ENGINE_KEY_INSERT	GLFW_KEY_INSERT
#define SAULE_ENGINE_KEY_DELETE	GLFW_KEY_DELETE
#define SAULE_ENGINE_KEY_RIGHT	GLFW_KEY_RIGHT
#define SAULE_ENGINE_KEY_LEFT	GLFW_KEY_LEFT
#define SAULE_ENGINE_KEY_DOWN	GLFW_KEY_DOWN
#define SAULE_ENGINE_KEY_UP	GLFW_KEY_UP
#define SAULE_ENGINE_KEY_PAGE_UP	GLFW_KEY_PAGE_UP
#define SAULE_ENGINE_KEY_PAGE_DOWN	GLFW_KEY_PAGE_DOWN
#define SAULE_ENGINE_KEY_HOME	GLFW_KEY_HOME
#define SAULE_ENGINE_KEY_END	GLFW_KEY_END
#define SAULE_ENGINE_KEY_CAPS_LOCK	GLFW_KEY_CAPS_LOCK
#define SAULE_ENGINE_KEY_SCROLL_LOCK	GLFW_KEY_SCROLL_LOCK
#define SAULE_ENGINE_KEY_NUM_LOCK	GLFW_KEY_NUM_LOCK
#define SAULE_ENGINE_KEY_PRINT_SCREEN	GLFW_KEY_PRINT_SCREEN
#define SAULE_ENGINE_KEY_PAUSE	GLFW_KEY_PAUSE
#define SAULE_ENGINE_KEY_F1	GLFW_KEY_F1
#define SAULE_ENGINE_KEY_F2	GLFW_KEY_F2
#define SAULE_ENGINE_KEY_F3	GLFW_KEY_F3
#define SAULE_ENGINE_KEY_F4	GLFW_KEY_F4
#define SAULE_ENGINE_KEY_F5	GLFW_KEY_F5
#define SAULE_ENGINE_KEY_F6	GLFW_KEY_F6
#define SAULE_ENGINE_KEY_F7	GLFW_KEY_F7
#define SAULE_ENGINE_KEY_F8	GLFW_KEY_F8
#define SAULE_ENGINE_KEY_F9	GLFW_KEY_F9
#define SAULE_ENGINE_KEY_F10	GLFW_KEY_F10
#define SAULE_ENGINE_KEY_F11	GLFW_KEY_F11
#define SAULE_ENGINE_KEY_F12	GLFW_KEY_F12
#define SAULE_ENGINE_KEY_F13	GLFW_KEY_F13
#define SAULE_ENGINE_KEY_F14	GLFW_KEY_F14
#define SAULE_ENGINE_KEY_F15	GLFW_KEY_F15
#define SAULE_ENGINE_KEY_F16	GLFW_KEY_F16
#define SAULE_ENGINE_KEY_F17	GLFW_KEY_F17
#define SAULE_ENGINE_KEY_F18	GLFW_KEY_F18
#define SAULE_ENGINE_KEY_F19	GLFW_KEY_F19
#define SAULE_ENGINE_KEY_F20	GLFW_KEY_F20
#define SAULE_ENGINE_KEY_F21	GLFW_KEY_F21
#define SAULE_ENGINE_KEY_F22	GLFW_KEY_F22
#define SAULE_ENGINE_KEY_F23	GLFW_KEY_F23
#define SAULE_ENGINE_KEY_F24	GLFW_KEY_F24
#define SAULE_ENGINE_KEY_F25	GLFW_KEY_F25
#define SAULE_ENGINE_KEY_KP_0	GLFW_KEY_KP_0
#define SAULE_ENGINE_KEY_KP_1	GLFW_KEY_KP_1
#define SAULE_ENGINE_KEY_KP_2	GLFW_KEY_KP_2
#define SAULE_ENGINE_KEY_KP_3	GLFW_KEY_KP_3
#define SAULE_ENGINE_KEY_KP_4	GLFW_KEY_KP_4
#define SAULE_ENGINE_KEY_KP_5	GLFW_KEY_KP_5
#define SAULE_ENGINE_KEY_KP_6	GLFW_KEY_KP_6
#define SAULE_ENGINE_KEY_KP_7	GLFW_KEY_KP_7
#define SAULE_ENGINE_KEY_KP_8	GLFW_KEY_KP_8
#define SAULE_ENGINE_KEY_KP_9	GLFW_KEY_KP_9
#define SAULE_ENGINE_KEY_KP_DECIMAL	GLFW_KEY_KP_DECIMAL
#define SAULE_ENGINE_KEY_KP_DIVIDE	GLFW_KEY_KP_DIVIDE
#define SAULE_ENGINE_KEY_KP_MULTIPLY	GLFW_KEY_KP_MULTIPLY
#define SAULE_ENGINE_KEY_KP_SUBTRACT	GLFW_KEY_KP_SUBTRACT
#define SAULE_ENGINE_KEY_KP_ADD	GLFW_KEY_KP_ADD
#define SAULE_ENGINE_KEY_KP_ENTER	GLFW_KEY_KP_ENTER
#define SAULE_ENGINE_KEY_KP_EQUAL	GLFW_KEY_KP_EQUAL
#define SAULE_ENGINE_KEY_LEFT_SHIFT	GLFW_KEY_LEFT_SHIFT
#define SAULE_ENGINE_KEY_LEFT_CONTROL	GLFW_KEY_LEFT_CONTROL
#define SAULE_ENGINE_KEY_LEFT_ALT	GLFW_KEY_LEFT_ALT
#define SAULE_ENGINE_KEY_LEFT_SUPER	GLFW_KEY_LEFT_SUPER
#define SAULE_ENGINE_KEY_RIGHT_SHIFT	GLFW_KEY_RIGHT_SHIFT
#define SAULE_ENGINE_KEY_RIGHT_CONTROL	GLFW_KEY_RIGHT_CONTROL
#define SAULE_ENGINE_KEY_RIGHT_ALT	GLFW_KEY_RIGHT_ALT
#define SAULE_ENGINE_KEY_RIGHT_SUPER	GLFW_KEY_RIGHT_SUPER
#define SAULE_ENGINE_KEY_MENU	GLFW_KEY_MENU
#define SAULE_ENGINE_KEY_LAST	SAULE_ENGINE_KEY_MENU

/*
	Enable/Disable Define
*/
#define SAULE_ENGINE_DEBUG_LOG 1

#endif /* __SAULE_ENGINE_DEFINE_HPP__ */